In [1]:
import pandas as pd
import os
import json

# READING CSV FILE

In [4]:
csv="C:\\Users\\jothika\\joe\\finance.csv"

In [5]:
df_csv = pd.read_csv(csv)

In [6]:
df_csv

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

# READING JSON FILE

In [7]:
json_path="C:\\Users\\jothika\\joe\\colors.json"

In [8]:
with open(json_path,"r")as f:
    raw_data=json.load(f)

In [9]:
df_json=pd.json_normalize(raw_data)

In [10]:
df_json

                                              colors
0  [{'name': 'Black', 'hex': '#000000', 'rgb': {'...

# READING PARQUET FILE

In [11]:
parquet_path="C:\\Users\\jothika\\joe\\iris.parquet"

In [12]:
df_parquet=pd.read_parquet(parquet_path)

In [13]:
df_parquet

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]